[package]
name = "example"
version.workspace = true
edition.workspace = true

[dependencies]
slint = { workspace = true }

[build-dependencies]
slint-icons = { path = ".." }
slint-build = { workspace = true }
