import { Icon, IconData, IconTheme } from "icon.slint";
export { Icon, IconData, IconTheme }

import { MaterialIcons } from "material/filled.slint";
export { MaterialIcons }

import { MaterialIconsOutlined } from "material/outlined.slint";
export { MaterialIconsOutlined }

import { MaterialIconsRound } from "material/round.slint";
export { MaterialIconsRound }

import { MaterialIconsSharp } from "material/sharp.slint";
export { MaterialIconsSharp }

import { MaterialIconsTwoTone } from "material/two_tone.slint";
export { MaterialIconsTwoTone }
